<x-guest-layout>
    <div class="mb-8 text-center lg:text-right"><div class="mx-auto mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-orange-500 text-2xl font-black text-white lg:mx-0">خ</div><h1 class="text-3xl font-black">تسجيل الدخول</h1><p class="mt-2 text-sm text-slate-400">أدخل بيانات حسابك للوصول إلى لوحة الخواجة.</p></div>
    @if($errors->any())<div class="mb-5 rounded-2xl border border-rose-500/20 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ route('login') }}" class="space-y-5" x-data="{show:false, loading:false}" @submit="loading=true">
        @csrf
        <div><label for="username" class="mb-2 block text-sm font-semibold text-slate-200">اسم المستخدم</label><input id="username" name="username" value="{{ old('username') }}" required autofocus autocomplete="username" class="w-full rounded-2xl border border-slate-700 bg-slate-950/70 px-4 py-3.5 text-white outline-none transition focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20" placeholder="مثال: admin"></div>
        <div><div class="mb-2 flex items-center justify-between"><label for="password" class="block text-sm font-semibold text-slate-200">كلمة المرور</label><a href="{{ route('password.request') }}" class="text-xs text-orange-400 hover:text-orange-300">نسيت كلمة المرور؟</a></div><div class="relative"><input id="password" :type="show ? 'text' : 'password'" name="password" required autocomplete="current-password" class="w-full rounded-2xl border border-slate-700 bg-slate-950/70 px-4 py-3.5 pl-14 text-white outline-none transition focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20" placeholder="8 أحرف على الأقل"><button type="button" @click="show=!show" class="absolute left-2 top-1/2 -translate-y-1/2 rounded-xl px-3 py-2 text-xs text-slate-400 hover:bg-white/5 hover:text-white">إظهار</button></div></div>
        <label class="flex items-center gap-2 text-sm text-slate-400"><input type="checkbox" name="remember" value="1" class="rounded border-slate-700 bg-slate-950 text-orange-500 focus:ring-orange-500"><span>تذكرني على هذا الجهاز</span></label>
        <button :disabled="loading" class="flex w-full items-center justify-center gap-2 rounded-2xl bg-orange-500 px-5 py-3.5 font-extrabold text-white shadow-lg shadow-orange-500/20 transition hover:bg-orange-400 disabled:cursor-not-allowed disabled:opacity-60"><span x-show="!loading">دخول إلى النظام</span><span x-show="loading">جارٍ تسجيل الدخول...</span></button>
    </form>
    <div class="mt-7 rounded-2xl border border-white/10 bg-white/5 p-4 text-xs text-slate-400"><div class="font-bold text-slate-200">حساب التجربة</div><div class="mt-2 grid grid-cols-2 gap-2"><span>المستخدم: admin</span><span>كلمة المرور: password</span></div></div>
</x-guest-layout>
