<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
<?php $__env->startSection('page_title','تفاصيل الطلب'); ?>
<div class="mx-auto max-w-6xl space-y-5">
    <div class="rounded-3xl bg-gradient-to-l from-slate-950 via-slate-900 to-orange-700 p-6 text-white shadow-xl md:p-8"><div class="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><div class="text-sm font-semibold text-orange-200"><?php echo e($order->order_number); ?></div><h1 class="mt-2 text-3xl font-black"><?php echo e($order->customer_name_snapshot ?: $order->customer?->name); ?></h1><div class="mt-2 text-sm text-white/70"><?php echo e($order->customer_phone_snapshot ?: $order->customer?->phone); ?> · <?php echo e($order->district?->name); ?></div></div><div class="flex gap-2"><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('update',$order)): ?><a href="<?php echo e(route('orders.edit',$order)); ?>" class="rounded-2xl bg-white px-4 py-2.5 text-sm font-black text-slate-950">تعديل</a><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete',$order)): ?><form method="POST" action="<?php echo e(route('orders.destroy',$order)); ?>" onsubmit="return confirm('هل تريد حذف الطلب؟')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-2.5 text-sm font-bold text-rose-700">حذف</button></form><?php endif; ?></div></div></div>

    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">الحالة</div><div class="mt-1 font-black"><?php echo e($order->statusLabel()); ?></div></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">الأولوية</div><div class="mt-1 font-black"><?php echo e($order->priorityLabel()); ?></div></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">السائق</div><div class="mt-1 font-black"><?php echo e($order->driver?->name ?? 'غير مسند'); ?></div></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">أجرة التوصيل</div><div class="mt-1 font-black"><?php echo e(number_format($order->delivery_fee,0)); ?> ل.س</div></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">الدفع</div><div class="mt-1 font-black"><?php echo e($order->paymentMethodLabel()); ?> · <?php echo e($order->paymentStatusLabel()); ?></div></div></div>

    <div class="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><div class="space-y-5"><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black">تفاصيل الطلب</h2><p class="mt-4 whitespace-pre-line leading-8 text-slate-600"><?php echo e($order->order_details ?: 'لا توجد تفاصيل.'); ?></p><?php if($order->driver_notes): ?><div class="mt-5 rounded-2xl border border-orange-100 bg-orange-50 p-4"><div class="text-xs font-bold text-orange-600">ملاحظات للموصل</div><div class="mt-1 whitespace-pre-line text-sm leading-7 text-orange-950"><?php echo e($order->driver_notes); ?></div></div><?php endif; ?></div><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black">سجل الحالة</h2><div class="mt-5 space-y-4"><?php $__empty_1 = true; $__currentLoopData = $order->statusHistory->sortByDesc('created_at'); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $event): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="flex gap-3"><div class="mt-1 h-3 w-3 shrink-0 rounded-full bg-orange-500"></div><div><div class="font-bold"><?php echo e($event->status_to ? (\App\Models\Order::STATUSES[$event->status_to] ?? $event->status_to) : 'تحديث'); ?></div><div class="mt-1 text-sm text-slate-500"><?php echo e($event->note ?: 'بدون ملاحظة'); ?> · <?php echo e($event->created_at?->format('Y-m-d H:i')); ?></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-slate-400">لا يوجد سجل.</p><?php endif; ?></div></div></div>

    <div class="space-y-5"><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black">التحصيل</h2><div class="mt-4 space-y-3"><div class="flex justify-between"><span class="text-slate-500">أجرة التوصيل</span><span class="font-bold"><?php echo e(number_format($order->delivery_fee,0)); ?> ل.س</span></div><div class="flex justify-between"><span class="text-slate-500">المدفوع</span><span class="font-bold text-emerald-600"><?php echo e(number_format((float)$order->payments->where('status','paid')->sum('amount'),0)); ?> ل.س</span></div><div class="flex justify-between border-t pt-3"><span class="font-bold text-slate-700">المتبقي</span><span class="font-black text-rose-600"><?php echo e(number_format($order->remainingAmount(),0)); ?> ل.س</span></div></div><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('manage-finances')): ?><?php if($order->remainingAmount()>0): ?><form method="POST" action="<?php echo e(route('orders.payments.store',$order)); ?>" class="mt-5 space-y-3"><?php echo csrf_field(); ?><input name="amount" type="number" min="0.01" max="<?php echo e($order->remainingAmount()); ?>" step="0.01" placeholder="قيمة الدفعة" required class="w-full rounded-2xl border-slate-200"><select name="method" class="w-full rounded-2xl border-slate-200"><option value="cash">نقدي</option><option value="transfer">تحويل</option></select><input name="reference_no" placeholder="رقم مرجع (اختياري)" class="w-full rounded-2xl border-slate-200"><button class="w-full rounded-2xl bg-orange-500 px-4 py-2.5 font-bold text-white">تسجيل دفعة</button></form><?php endif; ?> <?php endif; ?></div><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black">بيانات التسليم</h2><div class="mt-4 space-y-3 text-sm"><div><span class="text-slate-400">العنوان</span><div class="mt-1 font-semibold"><?php echo e($order->address_snapshot ?: $order->customer?->address ?: 'غير محدد'); ?></div></div><div><span class="text-slate-400">المنطقة</span><div class="mt-1 font-semibold"><?php echo e($order->district?->name ?? 'غير محددة'); ?></div></div></div></div></div></div>
</div></div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH C:\Users\HP\Downloads\al-khawaja-final-v2-full\al-khawaja-delivery-full\resources\views/orders/show.blade.php ENDPATH**/ ?>