<x-app-layout>
@section('page_title','تفاصيل الطلب')
<div class="mx-auto max-w-6xl space-y-5">
    <div class="rounded-3xl bg-gradient-to-l from-slate-950 via-slate-900 to-orange-700 p-6 text-white shadow-xl md:p-8"><div class="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><div class="text-sm font-semibold text-orange-200">{{ $order->order_number }}</div><h1 class="mt-2 text-3xl font-black">{{ $order->customer_name_snapshot ?: $order->customer?->name }}</h1><div class="mt-2 text-sm text-white/70">{{ $order->customer_phone_snapshot ?: $order->customer?->phone }} · {{ $order->district?->name }}</div></div><div class="flex gap-2">@can('update',$order)<a href="{{ route('orders.edit',$order) }}" class="rounded-2xl bg-white px-4 py-2.5 text-sm font-black text-slate-950">تعديل</a>@endcan @can('delete',$order)<form method="POST" action="{{ route('orders.destroy',$order) }}" onsubmit="return confirm('هل تريد حذف الطلب؟')">@csrf @method('DELETE')<button class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-2.5 text-sm font-bold text-rose-700">حذف</button></form>@endcan</div></div></div>

    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">الحالة</div><div class="mt-1 font-black">{{ $order->statusLabel() }}</div></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">الأولوية</div><div class="mt-1 font-black">{{ $order->priorityLabel() }}</div></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">السائق</div><div class="mt-1 font-black">{{ $order->driver?->name ?? 'غير مسند' }}</div></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">أجرة التوصيل</div><div class="mt-1 font-black">{{ number_format($order->delivery_fee,0) }} ل.س</div></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="text-xs text-slate-400">الدفع</div><div class="mt-1 font-black">{{ $order->paymentMethodLabel() }} · {{ $order->paymentStatusLabel() }}</div></div></div>

    <div class="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><div class="space-y-5"><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black">تفاصيل الطلب</h2><p class="mt-4 whitespace-pre-line leading-8 text-slate-600">{{ $order->order_details ?: 'لا توجد تفاصيل.' }}</p>@if($order->driver_notes)<div class="mt-5 rounded-2xl border border-orange-100 bg-orange-50 p-4"><div class="text-xs font-bold text-orange-600">ملاحظات للموصل</div><div class="mt-1 whitespace-pre-line text-sm leading-7 text-orange-950">{{ $order->driver_notes }}</div></div>@endif</div><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black">سجل الحالة</h2><div class="mt-5 space-y-4">@forelse($order->statusHistory->sortByDesc('created_at') as $event)<div class="flex gap-3"><div class="mt-1 h-3 w-3 shrink-0 rounded-full bg-orange-500"></div><div><div class="font-bold">{{ $event->status_to ? (\App\Models\Order::STATUSES[$event->status_to] ?? $event->status_to) : 'تحديث' }}</div><div class="mt-1 text-sm text-slate-500">{{ $event->note ?: 'بدون ملاحظة' }} · {{ $event->created_at?->format('Y-m-d H:i') }}</div></div></div>@empty<p class="text-slate-400">لا يوجد سجل.</p>@endforelse</div></div></div>

    <div class="space-y-5"><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black">التحصيل</h2><div class="mt-4 space-y-3"><div class="flex justify-between"><span class="text-slate-500">أجرة التوصيل</span><span class="font-bold">{{ number_format($order->delivery_fee,0) }} ل.س</span></div><div class="flex justify-between"><span class="text-slate-500">المدفوع</span><span class="font-bold text-emerald-600">{{ number_format((float)$order->payments->where('status','paid')->sum('amount'),0) }} ل.س</span></div><div class="flex justify-between border-t pt-3"><span class="font-bold text-slate-700">المتبقي</span><span class="font-black text-rose-600">{{ number_format($order->remainingAmount(),0) }} ل.س</span></div></div>@can('manage-finances')@if($order->remainingAmount()>0)<form method="POST" action="{{ route('orders.payments.store',$order) }}" class="mt-5 space-y-3">@csrf<input name="amount" type="number" min="0.01" max="{{ $order->remainingAmount() }}" step="0.01" placeholder="قيمة الدفعة" required class="w-full rounded-2xl border-slate-200"><select name="method" class="w-full rounded-2xl border-slate-200"><option value="cash">نقدي</option><option value="transfer">تحويل</option></select><input name="reference_no" placeholder="رقم مرجع (اختياري)" class="w-full rounded-2xl border-slate-200"><button class="w-full rounded-2xl bg-orange-500 px-4 py-2.5 font-bold text-white">تسجيل دفعة</button></form>@endif @endcan</div><div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black">بيانات التسليم</h2><div class="mt-4 space-y-3 text-sm"><div><span class="text-slate-400">العنوان</span><div class="mt-1 font-semibold">{{ $order->address_snapshot ?: $order->customer?->address ?: 'غير محدد' }}</div></div><div><span class="text-slate-400">المنطقة</span><div class="mt-1 font-semibold">{{ $order->district?->name ?? 'غير محددة' }}</div></div></div></div></div></div>
</div></div>
</x-app-layout>
